# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bynn < Formula
  desc "Command-line interface for the BYNN Intelligence API"
  homepage "https://bynn.com"
  version "0.1.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Bynn-Intelligence/bynn-cli/releases/download/v0.1.0/bynn_0.1.0_darwin_amd64.tar.gz"
      sha256 "1ae011e150694d249d839f61d30864615e3308167f4581478ccee02f43087d3e"

      define_method(:install) do
        bin.install "bynn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Bynn-Intelligence/bynn-cli/releases/download/v0.1.0/bynn_0.1.0_darwin_arm64.tar.gz"
      sha256 "10eda346e7ae89787f777b3fc29968e5d58574a730b8ce1deefb4a7372deeb38"

      define_method(:install) do
        bin.install "bynn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bynn-Intelligence/bynn-cli/releases/download/v0.1.0/bynn_0.1.0_linux_amd64.tar.gz"
      sha256 "7d47ed41074ff76fe92cfc5bab46f786fddc9fb133d6d01411a5ffae7b558bce"
      define_method(:install) do
        bin.install "bynn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bynn-Intelligence/bynn-cli/releases/download/v0.1.0/bynn_0.1.0_linux_arm64.tar.gz"
      sha256 "122cdfe1357d6388c6cb47151c8a8febe44dcb295942cc0593a05ca8b44bec99"
      define_method(:install) do
        bin.install "bynn"
      end
    end
  end

  test do
    system "#{bin}/bynn", "version"
  end
end
