# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bynn < Formula
  desc "Command-line interface for the BYNN Intelligence API"
  homepage "https://bynn.com"
  version "0.3.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Bynn-Intelligence/bynn-cli/releases/download/v0.3.0/bynn_0.3.0_darwin_amd64.tar.gz"
      sha256 "4cce2d4f6cb4eb01c1445666062f84e27304ce7ec2e3de47030ee53179f433aa"

      define_method(:install) do
        bin.install "bynn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Bynn-Intelligence/bynn-cli/releases/download/v0.3.0/bynn_0.3.0_darwin_arm64.tar.gz"
      sha256 "530a85074c6cfe988a2b1edb07c51adbdce88350adbd8af39ee8687f0f930ef6"

      define_method(:install) do
        bin.install "bynn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bynn-Intelligence/bynn-cli/releases/download/v0.3.0/bynn_0.3.0_linux_amd64.tar.gz"
      sha256 "030383a7869d529d79e3f76400275d347541430d574842ef7ef5aca292c77026"
      define_method(:install) do
        bin.install "bynn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bynn-Intelligence/bynn-cli/releases/download/v0.3.0/bynn_0.3.0_linux_arm64.tar.gz"
      sha256 "12ad6eaa89734e1eb234512394fe6f6b6a128872ee02ff7bec7a45edf4b4d975"
      define_method(:install) do
        bin.install "bynn"
      end
    end
  end

  test do
    system "#{bin}/bynn", "version"
  end
end
