# This file was generated by GoReleaser. DO NOT EDIT.
cask "bynn" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "e277de85380043a4c79a3bbe96aa87591a6550863b7b7f4f604c75acd930ccfb"
      url "https://github.com/Bynn-Intelligence/bynn-cli/releases/download/v#{version}/bynn_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "947f3d3f0566e319dfef4b7e0c83589a6f4bf516be3c871c8e5966cb11a90dfd"
      url "https://github.com/Bynn-Intelligence/bynn-cli/releases/download/v#{version}/bynn_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "de4d81774a4df083029a60bff171c66e88fbd6f663e90b629a8cbcac60de95b7"
      url "https://github.com/Bynn-Intelligence/bynn-cli/releases/download/v#{version}/bynn_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bcc5b3b9fae0759ef0945433ef2ac45550df55021013398227c082639bff84a0"
      url "https://github.com/Bynn-Intelligence/bynn-cli/releases/download/v#{version}/bynn_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bynn"
  desc "Command-line interface for the BYNN Intelligence API"
  homepage "https://bynn.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bynn"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bynn"]
    end
  end

  # No zap stanza required

end
