# This file was generated by GoReleaser. DO NOT EDIT.
cask "bynn" do
  version "0.3.3"

  on_macos do
    on_intel do
      sha256 "b5a27ec4ddf820caf55e41151680c85d820de0f960eaf63c94d457fd3e1758a1"
      url "https://github.com/Bynn-Intelligence/bynn-cli/releases/download/v#{version}/bynn_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a76a4a1063f5d965fa99eb59700f811a880049ecfedcb98be63e772961d7c454"
      url "https://github.com/Bynn-Intelligence/bynn-cli/releases/download/v#{version}/bynn_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eeb510b50254720f5bd6fa5f8a8e867ab3a18cff04ee2b2095be6a2f8c7f0a54"
      url "https://github.com/Bynn-Intelligence/bynn-cli/releases/download/v#{version}/bynn_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "370e3e37b860be046b8f401d1831a6947d676a861b1815f074ed983a32f17297"
      url "https://github.com/Bynn-Intelligence/bynn-cli/releases/download/v#{version}/bynn_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bynn"
  desc "Command-line interface for the BYNN Intelligence API"
  homepage "https://bynn.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bynn"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bynn"]
    end
  end

  # No zap stanza required

end
